### PR TITLE
chore: update compose version to 1.5.0-beta01

### PR DESCRIPTION
**Pull request by amanv8060**

### CODE REVIEW

**Comment by bentrengrove** [comment]
We don't normally do this unless an Accompanist library is experiencing a bug. If you use Compose 1.5-beta01 in your project then it will automatically get upgraded transitively.

Is not targetting beta01 causing you an issue?

**Comment by bentrengrove** [comment]
I'm going to close this for now as this happens as part of the release process but if not targetting beta01 causes you an issue then please file an issue.

**Comment by bentrengrove** [comment]
Was this an attempt to fix #1636? Sorry i missed that first, thank you for trying to fix that. It really is appreciated. 

We wouldn't be able to merge this as is because of the bump to navigation to 2.7.0 and also the version number gets changed as part of the release process not through a PR like this. Normally I would leave comments for you to fix this up so we could merge it in but seeing as that crash is affecting a lot of people I am going to do this PR myself to speed up the process.

Thanks again and sorry I couldn't merge it in this time.

**Comment by amanv8060** [comment]
> Was this an attempt to fix https://github.com/google/accompanist/issues/1636?

Yup, sample app didn't reproduce error after upgrading the compose, compiler and Kotlin versions, and copying the exact library into the app as a module also didn't reproduce crash.

Also, would the navigation version be upgraded as part of the deprecation process for AnimatedNavHost? Is there a process for this, or can I create a PR after this release?

**Comment by bentrengrove** [comment]
Yes, navigation will be upgraded as part of the deprecation process which is planned. We will handle that one but thank you for the offer.

**Pull request closed without merging**
