### PR TITLE
[Docs] Fix multiple formatting errors

### PR DESCRIPTION
**Pull request by msfjarvis**
Some drive-by fixes for broken links and invalid formatting

### CODE REVIEW

**Comment by alexvanyo** [comment]
@ricknout looks related to #1427 ?

**Comment by msfjarvis** [comment]
I've rebased this PR to remove the overlapping parts from Nick's PR since that has been merged.

**Comment by alexvanyo** [comment]
Thanks for the contribution and rebasing, looks good to me!

**Review by alexvanyo — APPROVED** [review]

**Comment by ricknout** [comment]
Sorry, I initially missed this. Thanks, LGTM!

**Review by ricknout — APPROVED** [review]

**Pull request merged**
