### PR TITLE
Rollback navigation upgrade to latest stable

### LINKED ISSUE #1552: [Navigation Material] Current release 0.30.0 ships navigation-compose alpha
**Description**
Current accompanist stable release 0.30.0 ships the navigation-compose:2.6.0-alpha07. We have an internal policy that we dont want to alpha versions without an important reason. This includes also transitive dependencies.

Was this commit intended and what was the reason?
https://github.com/google/accompanist/commit/c1ac4cb0a1bf4d2e01e7def6a3479204805f48d0

**Steps to reproduce**

**Expected behavior** 
Stable releases only ships stable transitive dependencies or has a valid reason to depend on beta/alpha versions.

**Additional context**

### PR DESCRIPTION
**Pull request by bentrengrove**
Fixes #1552

### CODE REVIEW

**Comment by bentrengrove** [comment]
Looks like that gradle issue still exists. @jossiwolf, you need 2.6.0 for your work right?

**Comment by jossiwolf** [comment]
@bentrengrove I don't think we need any APIs or features specifically, but there have been quite a few important bugfixes. Tbh I think it's fine to depend on an alpha version in Accompanist, we do the same with other AndroidX dependencies. Do you think we should depend on a stable Nav version instead?

cc @jbw0033

**Comment by G00fY2** [comment]
@jossiwolf I heavily disagree on using transitive unstable dependencies in stable releases. Thats also not the case for any other official library I am aware of (also not AndroidX deps).
The consumers should decide wether the bugfixes are important and justify using the alpha release.

E.g. we use [this check](https://gist.github.com/G00fY2/c852322a18b187f40bb884a85065c57f) (inspired by [this](https://discuss.gradle.org/t/failonversionconflict-only-for-certain-dependencies/29375)  Gradle discussion). Currently Accompanist is the only dependency which violates the check.

**Comment by JohannesPtaszyk** [comment]
Have to agree with @G00fY2. Transitive unstable dependencies in stable releases should be disallowed.

**Comment by serhii-pokrovskyi** [comment]
> We will be rolling back the navigation dependency to the last stable version and doing another Accompanist stable release.

any chances that this will fix?
I think that they are related
#1558

**Review by jossiwolf — APPROVED** [review]

**Pull request merged**
