### PR TITLE
Migrate AGP from 8.0.0 to 8.0.1

### PR DESCRIPTION
**Pull request by stevan-milovanovic**
Following up https://github.com/google/accompanist/issues/1616

Migrating AGP from 8.0.0 to 8.0.1 and resolving TODO: Remove when fixed https://github.com/gradle/gradle/issues/24037

### CODE REVIEW

**Comment by bentrengrove** [comment]
Thanks for the contribution! We are currently in the process of migrating to kts gradle files as part of #1578 but I don't see why we can't merge this in the mean time.

Please just fix up that merge conflict

**Comment by stevan-milovanovic** [comment]
You're welcome. Sounds good 👍 I fixed them up, should be good to go 😄

**Comment by stevan-milovanovic** [comment]
@bentrengrove sorry for the delay, I updated the changes.

**Comment by bentrengrove** [comment]
Sorry, as mentioned you are working at the same time as the migration to KTS so this now conflicts again. I might close this for now unfortunately as by the end of the migration the bump from 8.0.0 to 8.0.1 should be trivial

**Pull request closed without merging**
