### PR TITLE
Update README.md to include swipe-to-refresh link

### PR DESCRIPTION
**Pull request by mr3y-the-programmer**
link  swipe-to-refresh library in README to be consistent with other libraries

### CODE REVIEW

**Comment by mr3y-the-programmer** [comment]
I've already signed it before but my email address is made private since then, so, I think I need to use github provided `no-reply` email address

**Comment by chrisbanes** [comment]
> I've already signed it before but my email address is made private since then, so, I think I need to use github provided `no-reply` email address

Hi, I don't see a CLA for your username in the system. Did you use a different account?

**Comment by mr3y-the-programmer** [comment]
Thanks @chrisbanes for your response!, I've already solved the problem

**Comment by mr3y-the-programmer** [comment]
@googlebot I signed it!

**Comment by chrisbanes** [comment]
Cool, thanks!

**Pull request merged**
