### PR TITLE
[Pager] Fix formatting and improve pager documentation

### PR DESCRIPTION
**Pull request by MaximillianLeonov**

### CODE REVIEW

**Comment by bentrengrove** [comment]
This has already been fixed in #1561 but the docs only get generated with a new release so hasn't shown up yet.

**Comment by MaximillianLeonov** [comment]
@bentrengrove,

Hi, Ben. Are these issues the same? You can see the issue below in the screenshot for which I provided the fix, which is caused by the missing four spaces indentation. Correct me if I am wrong, please.

**Actual:**
image

**Expected:**
image

**Comment by bentrengrove** [comment]
I believe it is the same issue, if it doesn't work I will come back and merge yours

**Review by bentrengrove — APPROVED** [review]
Looks like it is still broken so will merge this in. Thank you for the fix!

**Pull request merged**
