### PR TITLE
[navigation-material] expose sheetGesturesEnabled flag

### LINKED ISSUE #730: Provide a method to make the bottom sheet non-cancellable for some use-cases.
## Describe the bug
Provide a method to make the bottom sheet non-cancellable for some use-cases.

## Expected behaviour
When a user clicks the back button or the outside content of the bottom sheet, then it dismisses. However, there should be a way to control that behaviour based on a flag that the bottom sheet should not dismiss. It should only dismiss via calling ```navGraph.navigateBack()```.

## Environment:
 - Android OS version: [Android 11.0]
 - Device: [Samsung M20]
 - Accompanist version: [0.17.0]

### PR DESCRIPTION
**Pull request by amanv8060**
Fixes #730 

Expose sheetGesturesEnabled Flag

### CODE REVIEW

**Comment by ianhanniballake** [comment]
Similar to the [comment](https://github.com/google/accompanist/pull/1342#issuecomment-1250828716) on #1342, we'd want to make this available on a per destination level, not a global flag.

This may be easier said than done given the current state of `ModalBottomSheetLayout` (also as explained in that comment), but if it is possible, we'd be happy to merge a destination level flag in if you'd like to put up a new patch set.

**Comment by amanv8060** [comment]
Will give it a try, although it doesn't look easily possible.

**Comment by amanv8060** [comment]
@ianhanniballake, I have added a destination-level flag and updated the bottom sheet sample to demonstrate the same. I am a little unsure about the performance implications of this approach.

Can you take a look and let me know what you think?

If this looks good, I can try adding tests for this.

**Comment by jossiwolf** [comment]
@amanv8060, thanks for the PR!

I'd be interested to see if tests for the following scenarios (see the comment Ian linked) would pass:

> The concerns are about recreating the state in time when the value changes as the destination changes, but maybe it'd work. We'd want some good test coverage that tests
> 
> Navigating from a skipHalfExpanded = false to a skipHalfExpanded = false destination
> Navigating from a skipHalfExpanded = false to a skipHalfExpanded = true destination
> Navigating from a skipHalfExpanded = true to a skipHalfExpanded = false destination
> and ensures that the sheet opens up to the correct state.

If yes, we can look at performance a bit more. What concerns do you have here?

**Comment by amanv8060** [comment]
I will try adding tests for these cases.

**Comment by amanv8060** [comment]
cc/ @jossiwolf icymi

**Comment by VahidGarousi** [comment]
Would love to see this merged ✌️

**Comment by ianhanniballake** [comment]
With the release of [Compose Material 1.7.0-alpha04](https://developer.android.com/jetpack/androidx/releases/compose-material#1.7.0-alpha04), the Material team has added a new artifact: `androidx.compose.material:material-navigation`, which fully replaces Accompanist Navigation Material.

As such, we are closing all PRs here on Accompanist.

**Pull request closed without merging**
