### PR TITLE
Override default Intrinsics for Flow

### LINKED ISSUE #622: FlowRow affects Modifier.height(IntrinsicSize)
## Describe the bug
`FlowRow` somehow affects `Modifier.height(IntrinsicSize.Max)`, that's so resulting height is wrong

## To Reproduce
Use `LazyColumn` the items of which are some containers with `Modifier.height(IntrinsicSize.Max)` and including `FlowRow` with different items count.

Example:
```
@Composable
fun Screen() {
	val items = listOf<List<String>>(
		listOf("a", "b", "c"),
		listOf("a", "b", "c", "d"),
		listOf("a"),
		listOf("a", "b"),
		listOf("c")
	)
	LazyColumn {
		items(items) {
			Item(it)
		}
	}
}

@Composable
fun Item(strings: List<String>) {
	Box(
		modifier = Modifier
			.fillMaxWidth()
			.height(IntrinsicSize.Max)
	) {
		Spacer(
			modifier = Modifier
				.background(Color(Random.nextInt(), Random.nextInt(), Random.nextInt()))
				.width(4.dp)
				.fillMaxHeight()
				.align(Alignment.CenterStart)
		)
		FlowRow {
			strings.forEach {
				Text(text = it)
			}
		}
	}
}
```

## Expected behavior
(In accordance with example code) Resulting height of `Item` is equal to the height of `FlowRow`

## Actual behavior
`Item`'s height somehow depends on `FlowRow` items count.
image

## Environment:
 - Android OS version: Android 10
 - Device: Nokia 5.3
 - Accompanist version: 0.16.0
 - Compose version: 1.0.0

### PR DESCRIPTION
**Pull request by yasincidem**
Fixes #622

### CODE REVIEW

**Comment by chrisbanes** [comment]
Looks good, but please add some tests to verify the new behavior.

**Comment by yasincidem** [comment]
Okay, I will add tests.

**Comment by matejdro** [comment]
Is `maxIntrinsicHeight` intrinsic correct here?

Shouldn't that number, in column mode, calculate total height of the view?

**Comment by C5FR7Q** [comment]
Any update?

**Pull request closed without merging**
