### PR TITLE
[WebView] ✨ Expose the postUrl function via the WebView Composable

### LINKED ISSUE #1612: [WebView] postUrl not working anymore
**Description**
Since `0.29.1-alpha` update the postUrl() function is not working anymore

**Steps to reproduce**
I used to be able to use the old postUrl function the following way:
```
val state = rememberWebViewState("")
WebView(
    state = state,
    factory = {
        android.webkit.WebView(it).apply {
            postUrl(
                "https://google.com",
                "my_by_array_string".toByteArray()
            )
        }
    }
)
```
I am not sure if this was the correct way to post data but it was the only way I could get it working. Unfortunately, with the `0.29.1-alpha` release it broke.

**Expected behavior** 
I am able to do a postUrl call that also has a parameter called `byte[] postData`

### PR DESCRIPTION
**Pull request by MaxMichel2**
Adds the postUrl function to the WebView

Fixes #1612

### CODE REVIEW

**Comment by bentrengrove** [comment]
Thanks for this contribution, it's looking good! We would also need a test please to be able to merge this

**Comment by MaxMichel2** [comment]
Hey @bentrengrove,

I totally forgot about the test! That's my bad. It should be added now so feel free to check and come back to me with other changes if required.

**Review by bentrengrove — APPROVED** [review]
LGTM! Thanks for the contribution

**Comment by MaxMichel2** [comment]
It seems like the build failed for some reason. I'm not too sure on why that is however. I can take a look at the code if required 🤔

**Comment by bentrengrove** [comment]
```
e: file:///home/runner/work/accompanist/accompanist/web/src/main/java/com/google/accompanist/web/WebView.kt:332:5 Visibility must be specified in explicit API mode

e: file:///home/runner/work/accompanist/accompanist/web/src/main/java/com/google/accompanist/web/WebView.kt:577:5 Visibility must be specified in explicit API mode
e: file:///home/runner/work/accompanist/accompanist/web/src/main/java/com/google/accompanist/web/WebView.kt:700:1 Visibility must be specified in explicit API mode
```

It's running in explicit API mode so you probably just have to add `public` to all your assumed public methods and classes.

**Comment by MaxMichel2** [comment]
> ```
> e: file:///home/runner/work/accompanist/accompanist/web/src/main/java/com/google/accompanist/web/WebView.kt:332:5 Visibility must be specified in explicit API mode
> 
> e: file:///home/runner/work/accompanist/accompanist/web/src/main/java/com/google/accompanist/web/WebView.kt:577:5 Visibility must be specified in explicit API mode
> e: file:///home/runner/work/accompanist/accompanist/web/src/main/java/com/google/accompanist/web/WebView.kt:700:1 Visibility must be specified in explicit API mode
> ```
> 
> It's running in explicit API mode so you probably just have to add `public` to all your assumed public methods and classes.

It seems as though the lines don't reference anything specific on my side... You can check the lines in the PR but 332, 577 and 700 don't point to anything where I could add the `public` keyword unfortunately

I've tried running the build as configured in the github actions on my side and it works just fine so I'm wondering if I'm missing a config that you may have locally 🤔 

I also tried adding the explicit API mode locally but this seems to want keywords in many more places that what the build currently reports.

All help on this issue would be appreciated since I'd like to get this added soon ^^

**Pull request merged**
