### PR TITLE
PageState.targetPage didn't perform as we expected  when page offset between -0.5f and 0f.

### PR DESCRIPTION
**Pull request by MuffinMyHeart**
Fix the PagerState.targetPage when the currentPageOffset between -0.5f and 0f, the targetPage is currentPage + 1 which is wrong, it should be currentPage - 1.

### CODE REVIEW

**Comment by jakoss** [comment]
Can anyone take a look at this? Changes are minor and the impact is quite big. For now the indicator behavior is pretty much unacceptable :)

**Comment by andkulikov** [comment]
Hey!
I am ready to accept the fix for PagerState if you can remove the change HorizontalPagerWithOffsetTransition from it. Could you please clarify what do you mean by the picture can't move, as I expect the code using Modifier.offset to work correctly. We also can't just use a constant in pixels like 64 as this will mean it works differently on screens with different densities, that is why 36.dp was used in the original code

**Comment by MuffinMyHeart** [comment]
> Hey!
> I am ready to accept the fix for PagerState if you can remove the change HorizontalPagerWithOffsetTransition from it (ideally if you can also write a simple test for your change). Could you please clarify what do you mean by the picture can't move, as I expect the code using Modifier.offset to work correctly. We also can't just use a constant in pixels like 64 as this will mean it works differently on screens with different densities, that is why 36.dp was used in the original code

In my branch , HorizontalPagerWithOffsetTransition does't work correctly for some reason .But in master branch , the same code  works correctly and I have reverted the HorizontalPagerWithOffsetTransition. 
 I don't know how to test it , but I have passed all the test case the project PagerTest provides.
image

**Comment by MuffinMyHeart** [comment]
> Hey!
> I am ready to accept the fix for PagerState if you can remove the change HorizontalPagerWithOffsetTransition from it (ideally if you can also write a simple test for your change). Could you please clarify what do you mean by the picture can't move, as I expect the code using Modifier.offset to work correctly. We also can't just use a constant in pixels like 64 as this will mean it works differently on screens with different densities, that is why 36.dp was used in the original code

 In my branch , HorizontalPagerWithOffsetTransition does't work correctly for some reason .But in master branch , the same code  works correctly ,and I have reverted the HorizontalPagerWithOffsetTransition. 
I don't know how to write test code for this , but I have passed all the test case the pager project provides.
image

**Comment by jakoss** [comment]
What happened here? Is the pager indicator fixed in another pull request?

**Comment by MuffinMyHeart** [comment]
> What happened here? Is the pager indicator fixed in another pull request?

I don't understand, why I use android studio to commit my code with github token login , the  google-cla show me cla: no.
that commit didn't show my github account info, can you see that?

**Comment by MuffinMyHeart** [comment]
> What happened here? Is the pager indicator fixed in another pull request?

just like that , no my avatar, no my info.

**Comment by MuffinMyHeart** [comment]
> What happened here? Is the pager indicator fixed in another pull request?

image

just like that , no my avatar, no my info.

**Comment by MuffinMyHeart** [comment]
> What happened here? Is the pager indicator fixed in another pull request?

Some problems happened ,It took me a while. now I reopen it

**Review by andkulikov — APPROVED** [review]

**Comment by andkulikov** [comment]
Thanks

**Comment by jakoss** [comment]
@andkulikov Is there a plan to release bugfix stable-ish version with this?

**Pull request merged**
