### PR TITLE
[WebView] Fix issues with nested scroll dispatch in WebView

### LINKED ISSUE #1235: SwipeRefresh fails to detect gestures when Webview is used with SwipeRefresh
```kotlin
                val webViewState = rememberWebViewState("https://github.com")
                var webView: WebView? = remember {
                    null
                }
                val swipeRefreshState = rememberSwipeRefreshState(isRefreshing = false)
                SwipeRefresh(state = swipeRefreshState, onRefresh = {
                    swipeRefreshState.isRefreshing = true
                    webView?.reload()
                    swipeRefreshState.isRefreshing = false
                }) {
                    WebView(
                        state = webViewState,
                        onCreated = { webView0 ->
                            webView = webView0
                            setWebView(webView0)
                        }
                    )
                }
```

### LINKED ISSUE #1260: TopAppBar does not collapse with WebView
## Describe the bug
The Accompanist Webview "content" does scroll with the `TopAppBar` but the `TopAppBar` does not collapse on scroll. `TopAppBar` does collapse with other views, for example - https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary.

# Repo
https://github.com/jaredsburrows/android-gif-example

# Code
https://github.com/jaredsburrows/android-gif-example/blob/32d96e6d5b1575141c7b4ae57ec2a7c199303c33/app/src/main/java/com/burrowsapps/example/gif/ui/license/LicenseActivity.kt#L110

```kotlin
@Composable
fun DefaultPreview() {
  val navController = rememberNavController()
  val scrollBehavior = TopAppBarDefaults.enterAlwaysScrollBehavior(rememberTopAppBarScrollState())

  Scaffold(
    modifier = Modifier.nestedScroll(scrollBehavior.nestedScrollConnection),
    topBar = { TheToolbar(navController = navController, scrollBehavior = scrollBehavior) },
    content = { paddingValues ->

      val context = LocalContext.current
      val state =
        rememberWebViewState("https://appassets.androidplatform.net/assets/open_source_licenses.html")

      com.google.accompanist.web.WebView(
        state,
        modifier = Modifier.padding(innerPadding).nestedScroll(scrollBehavior.nestedScrollConnection),
        onCreated = { webView ->
        },
        client =  { }
      )
      
    }
  )
}
```

If I use a different view other than `WebView`, it will scroll like the example in the documentation.

### PR DESCRIPTION
**Pull request by bentrengrove**
Fixes #1260 
Fixes #1235

Wrapped the `WebView` in a `NestedScrollView` which seems to be the recommended method to deal with this in views.

Added a collapsing toolbar and swipe refresh to the sample in order to test it and it seems to work well.

### CODE REVIEW

**Comment by alitahabundle** [comment]
I have tried this and creates jiggly jumping behavior on topbar

**Comment by bentrengrove** [comment]
I'm going to need more details sorry. Did you just test the sample app? What device and android version?

**Comment by alexvanyo** [comment]
I was able to see some strange behavior as well, this is on a ZFold 2, API 31:

https://user-images.githubusercontent.com/4217560/184943172-22526e5b-5b7d-4d71-9dd8-5d57c2f3e790.mp4

**Comment by alitahabundle** [comment]
I have just see the comment, but yes, some sort of same thing happens like @alexvanyo published.

**Comment by bentrengrove** [comment]
Closing for now whilst I investigate

**Comment by rockyoung** [comment]
if wrapped by a `NestedScrollView`, we will face the next problem:
https://issuetracker.google.com/issues/37077954

**Pull request closed without merging**
