### PR TITLE
Add more convenient system ui control functions and sample.

### PR DESCRIPTION
**Pull request by RinOrz**
Fixed: #291 

- `var isStatusBarVisible`
- `var isNavigationBarVisible`
- `var isSystemBarsVisible`
- `fun setStatusBarDarkIcons`
- `fun setNavigationBarDarkIcons`
- `fun isDarkStatusBarIcons`
- `fun isDarkNavigationBarIcons`
- Add system ui controller sample

But currently there are some problems with the return values of `isStatusBarVisible`, `isNavigationBarVisible` and `isSystemBarsVisible`. I try to get the visibility of the system bars through `InsetsType.isVisible`, but they are not accurate. I use some other means to get them (but unfortunately they also don’t seem to be accurate). So I am considering changing **mutable property** to **function** and only provide the visibility settings of the system bars without returning the current visibility.

https://user-images.githubusercontent.com/58068445/115105672-fc305680-9f92-11eb-89f4-a296f735d070.mp4

### CODE REVIEW

**Comment by chrisbanes** [comment]
First of all, thanks for the PR, but...

> `isStatusBarVisible`, `isNavigationBarVisible` & `isSystemBarsVisible` 

These won't be allowed in. That's what the `WindowInsets` library is for, and detecting the whether the bars are visible or not is usually an anti-pattern.

> `setStatusBarDarkIcons`, `setNavigationBarDarkIcons`, `isDarkNavigationBarIcons()` & `isDarkStatusBarIcons()`

What's the use case here? I think most things are covered by `setNavigationBarColor()` & `setStatusBarColor()` but these could be useful.

**Comment by RinOrz** [comment]
> > `setStatusBarDarkIcons`, `setNavigationBarDarkIcons`, `isDarkNavigationBarIcons()` & `isDarkStatusBarIcons()`
> 
> What's the use case here? I think most things are covered by `setNavigationBarColor()` & `setStatusBarColor()` but these could be useful.

Sometimes we don’t always need to change status bar color, but only need to darken the icons. For example, the status bar color is always transparent but the background image will change.

**Comment by RinOrz** [comment]
> First of all, thanks for the PR, but...
> 
> > `isStatusBarVisible`, `isNavigationBarVisible` & `isSystemBarsVisible`
> 
> These won't be allowed in. That's what the `WindowInsets` library is for, and detecting the whether the bars are visible or not is usually an anti-pattern.

So should they be changed to `set**BarVisible(isVisible: Boolean = true)`?

**Comment by chrisbanes** [comment]
> > What's the use case here? I think most things are covered by `setNavigationBarColor()` & `setStatusBarColor()` but these could be useful.
> 
> Sometimes we don’t always need to change status bar color, but only need to darken the icons. For example, the status bar color is always transparent but the background image will change.

True, in that case please remove `isStatusBarVisible`, `isNavigationBarVisible` & `isSystemBarsVisible` and I'll take a look through the PR.

> So should they be changed to set**BarVisible(isVisible: Boolean = true)?

Maybe, I'm a bit worried that we're just creating a wrapper around [`WindowInsetsController`](https://developer.android.com/reference/androidx/core/view/WindowInsetsControllerCompat). Apps shouldn't be afraid to use Android APIs from within Compose, and the goal of `SystemUiController` isn't to be a copy of `WindowInsetsController`

**Comment by RinOrz** [comment]
> Maybe, I'm a bit worried that we're just creating a wrapper around [`WindowInsetsController`](https://developer.android.com/reference/androidx/core/view/WindowInsetsControllerCompat). Apps shouldn't be afraid to use Android APIs from within Compose, and the goal of `SystemUiController` isn't to be a copy of `WindowInsetsController`

But in the sense of the name of the `SystemUiController`, I think they have at least. In addition, personally, I hope to have a more convenient APIs in the Compose world.

**Pull request closed without merging**
