### PR TITLE
[Placeholder] Fix that a placeholder modifier is not changed on every recomposition

### LINKED ISSUE #466: [Placeholder] A placeholder modifier is not changed on every recomposition
## Describe the bug
A placeholder modifier with animated brush is not changed on every recomposition.
So if `animatedBrush` or `shape` is changed, it still shows as the first state.
The following is an example code.
```kt
var refreshing by remember { mutableStateOf(false) }
LaunchedEffect(refreshing) {
    if (refreshing) {
        delay(2000)
        refreshing = false
    }
}

SwipeRefresh(
    state = rememberSwipeRefreshState(isRefreshing = refreshing),
    onRefresh = { refreshing = true },
) {
    LazyColumn {
        if (refreshing.not()) {
            item {
                ListItem(
                    painter = rememberVectorPainter(Icons.Default.ArrowDownward),
                    text = "Pull down"
                )
            }
        }
        items(30) { index ->
            ListItem(
                painter = rememberGlidePainter(randomSampleImageUrl(index)),
                text = "Text",
                childModifier = Modifier.placeholder(
                    /**
                     *  If `visible` is not changed,
                     *  but `animatedBrush` or `shape` is changed,
                     *  it occurs!
                     */
                    visible = true,
                    animatedBrush = if (refreshing) fade() else shimmer(),
                    shape = if (refreshing) RectangleShape else CircleShape
                )
            )
        }
    }
}
```

## Expected behavior
When `animatedBrush` or `shape` is changed, the placeholder modifier should change.

## Screenshots?
| Before | After |
|---------------|--------------|
|  |  |

### PR DESCRIPTION
**Pull request by fornewid**
- Use `remember` with keys.
- Add more tests to validate recomposition situations.
- Add README and gradle.properties missing in #457.

Fixes #466.

| Before | After |
|---------------|--------------|
|  |  |

### CODE REVIEW

**Review by chrisbanes — APPROVED** [review]

**Comment by chrisbanes** [comment]
I have a ‘fix’ in the main branch for the tests timing out.

**Comment by fornewid** [comment]
@chrisbanes Thanks! I merged main branch to this.

**Comment by fornewid** [comment]
I think, `assertShape()` is not a stable API.
So I just checked the color of the vertices instead.

**Comment by fornewid** [comment]
In test (22, default), timeout occurred on SystemUiControllerTest without modification.
May I ask for "Re-run jobs"? :bow:

**Comment by chrisbanes** [comment]
No need, just decided to merge instead 👍

**Pull request merged**
